export const platformIpcChannels = {
  createSession: 'platform:create-session',
  openSession: 'platform:open-session',
  closeSession: 'platform:close-session',
  setBounds: 'platform:set-bounds',
  destroySession: 'platform:destroy-session',
  getSessionState: 'platform:get-session-state',
  event: 'platform:event',
  stateChanged: 'platform:state-changed',
  guestEvent: 'platform:guest-event',
  guestStateChanged: 'platform:guest-state-changed',
  guestLog: 'platform:guest-log',
  translateText: 'platform:translate-text',
  languageList: 'platform:language-list',
} as const
