/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    BrowserContainerHost: typeof import('./components/client/BrowserContainerHost.vue')['default']
    CaptureTimelinePanel: typeof import('./components/client/CaptureTimelinePanel.vue')['default']
    ClientShell: typeof import('./components/client/ClientShell.vue')['default']
    ContainerStatusBar: typeof import('./components/client/ContainerStatusBar.vue')['default']
    ContainerWorkspace: typeof import('./components/client/ContainerWorkspace.vue')['default']
    ConversationPanel: typeof import('./components/client/ConversationPanel.vue')['default']
    DefaultLayout: typeof import('./components/layout/DefaultLayout.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FeatureAppsView: typeof import('./components/client/FeatureAppsView.vue')['default']
    LoginModal: typeof import('./components/common/LoginModal.vue')['default']
    PlatformRail: typeof import('./components/client/PlatformRail.vue')['default']
    QuickReplyView: typeof import('./components/client/QuickReplyView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./components/client/SettingsView.vue')['default']
    ToolPanel: typeof import('./components/client/ToolPanel.vue')['default']
    TopStatusBar: typeof import('./components/client/TopStatusBar.vue')['default']
    WorkspaceHome: typeof import('./components/client/WorkspaceHome.vue')['default']
  }
}
